import React, { FC, useState } from "react";

interface LastResortWarnModalProps {
  onConfirm: () => void;
  onCancel: () => void;
}

const LastResortWarnModal: FC<LastResortWarnModalProps> = ({
  onConfirm,
  onCancel,
}) => {
  const [showWarning, setShowWarning] = useState(true);

  const handleOkay = () => {
    setShowWarning(false);
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-50">
      <div className="relative w-11/12 p-5 bg-white rounded-lg md:w-1/2">
        <div className="flex items-center justify-between mb-4">
          <h2 className="text-3xl font-bold text-red-600">Warning</h2>
          <button onClick={onCancel} className="text-lg font-bold text-black">
            &times;
          </button>
        </div>
        <div className="p-4">
          {showWarning ? (
            <div>
              <p className="text-lg font-semibold text-[#044677] mb-4">
                You are about to enable last resort translation. This is an
                emergency feature that provides translations for terms not found
                in the Grey-Box database by using artificial intelligence. As
                such, translations may be inaccurate. Please use discretion.
              </p>
              <div className="flex justify-end">
                <button
                  onClick={handleOkay}
                  className="bg-[#2e7c64] text-white font-bold py-2 px-4 rounded-lg hover:bg-[#256c54] transition-all"
                >
                  Okay
                </button>
              </div>
            </div>
          ) : (
            <>
              <p className="text-xl font-semibold text-[#044677] mb-4">
                Grey-Box cannot ensure the accuracy of last resort translations
                generated by this feature and as such, cannot ensure the safety
                of using/consuming substances provided by it.{" "}
                <span className="text-red-600 font-bold">
                  PLEASE CONSULT A PROFESSIONAL.
                </span>{" "}
                Do you consent to the potential risks and wish to enable this
                feature?
              </p>
              <div className="flex justify-between">
                <button
                  onClick={onConfirm}
                  className="bg-[#2e7c64] text-white font-bold py-2 px-4 rounded-lg hover:bg-[#256c54] transition-all"
                >
                  Yes
                </button>
                <button
                  onClick={onCancel}
                  className="bg-red-500 text-white font-bold py-2 px-4 rounded-lg hover:bg-red-600 transition-all"
                >
                  No
                </button>
              </div>
            </>
          )}
        </div>
      </div>
    </div>
  );
};

export default LastResortWarnModal;
